### PR TITLE
Added Cleanup layers for the containers

### PR DESCRIPTION
**Pull request by jjasghar**
Added a layer to clean up and remove things that are cached and would be
updated with an apt-get update anyway.

Signed-off-by: JJ Asghar <jj@chef.io>

### CODE REVIEW

**Comment by rastasheep** [comment]
@jjasghar Tnx, can you add cleanup command to the template file as well https://github.com/rastasheep/ubuntu-sshd/blob/master/Dockerfile.template ?

Idea of that template file is to be used for generating dockerfiles for every ubuntu version

**Comment by jjasghar** [comment]
Awesome. Do you mind multiple commits or squash to one?

**Comment by rastasheep** [comment]
Multiple commits are fine, tnx

**Comment by jjasghar** [comment]
Bump!

**Comment by rastasheep** [comment]
tnx for contribution!

**Pull request merged**
